<a href="https://colab.research.google.com/github/Srikanth-9492/My_python_notebook/blob/main/Numpy_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

27-05-2025

**Numpy Introduction**

In [ ]:
#what is Numpy?
#numpy is a core library for scientific computing in python
#what is the central object in numpy?
#Numpy - Array's
#what is Numpy?
#Array's are high performance multi dimensional objects which is designed for mathematical operations
#Array's are ordered, imuttable, and allows duplicate data


In [ ]:
#what are all different use cases of numpy?
"""1.  Dot Product/ Inner product
   2. Matric multiplication
   3. element wise matrix multiplication
   4. solving linear systems
   5. inverse
   6. determinent
   7. choose the random numbers
   8. statistics
   9. Broadcasting method """


** Installation of Numpy**

 what is pip?

 python package manager


 package ---> modules---> libraries----> inbuilt codes

In [ ]:
!pip install Numpy

In [ ]:
import numpy as np


In [ ]:
#check the version of numpy?
np.__version__

'2.0.2'

In [ ]:
#How many types of data structures do we have in numpy?
#There are 3 types
#1D--- Array's ---> Array's with zero columns and specific rows(axis 0)
#2D--- Array's ---> Array's with both rows(axis 0) and columns(axis 1)
#3D--- Array's ---> also known as Multidimensional arrays


**Central object in Numpy in Array**

In [ ]:
#How can we create an array?
#Array's can be created from existing data
#1D --- Array
l = [1,2,3,4,5,6]
a = np.array(l)
print(a)

[1 2 3 4 5 6]


In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
#I want to see the shape of the array
a.shape
#find the dtype of elements in the numpy array
a.dtype
#Find the dimensionality of an array
a.ndim
#Find the total no of elements present in array
a.size
#Find the memory size in bytes occupied by each element in array
a.itemsize

8

**Essential methods to create an array**

In [ ]:
t = (1,2,3,4,5,6)
b = np.array(t)
print(b)
print(type(b))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
#create an array from dictionary?
d1 ={
     'name':'Medha',
     'course':'data science'
}
c = np.array(d1)
print(c)

{'name': 'Medha', 'course': 'data science'}


In [ ]:
#create an array from the set?
s = {1,2,3,4,5,6,7,8}
d = np.array(s)
print(d)

{1, 2, 3, 4, 5, 6, 7, 8}


**Essential methods to access an array**

In [ ]:
a = np.array([1,2,3,4])
#print the list value
print(a[0])
#print 2,3 from above array
print(a[1:3])
#reverse the above array
print(a[::-1])

1
[2 3]
[4 3 2 1]


In [ ]:
#Array's are immutable we can replace the data but we cannot add new elements and we cannot remove elements from arrays.
a[2] = 5
print(a)

[1 2 5 4]


In [ ]:
#How can we add the new elements to the array?---> we can add by creating a new variable


**Element wise maths operation**

In [ ]:
b = np.array([6,7,8,9])
print(a+b)
#what is vector addition?
#when we apply addition on array of same length n dimensions---> is known as vector addition
#Note:-

[ 7  9 13 13]


In [ ]:
c = np.array([9])
print(b+c)
#What is broadcasting method?
#Adding a single element of an array with multiply elements in another array of same dimension is known as Broadcasting method


[15 16 17 18]


**Difference between Array and list**


In [ ]:
l = [1,2,3]
a = np.array(l)
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__

In [ ]:
#adding the elements in the list:
l.append(4)
print(l)

[1, 2, 3, 4]


In [ ]:
#add the element  in an array
b = np.array([5,6,7,8])
c = np.append(a,b)
print(c)

[1 2 3 5 6 7 8]


In [ ]:
"MISD---> Multiple input and single destination"


In [ ]:
#find the sort of below array's?
a = np.array([10,20,30,40,50,60])
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]


**Dot Product**

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
dot = 0
for i in range(len(a)):
  dot = dot + a[i]*b[i]
print(dot)

11


In [ ]:
#dot product is vector multiplication of elements and sum of the result
dot = np.dot(a,b)
print(dot)

11


In [ ]:
#manual method
c = a*b
d = np.sum(c)
print(d)

11


In [ ]:
#another method
e = a.dot(b)
print(e)

11


In [ ]:
f = a@b
print(f)

11


**Speed test b/w Array vs List**

In [ ]:
#import a time calculator to see the difference
from timeit import default_timer as timer
#create an random array
a = np.random.randn(1000)
b = np.random.randn(1000)
#convert the above array's
c = list(a)
d = list(b)
T = 1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i]
  return dot
def dot2():
  return np.dot(a,b)
#take the timer
start = timer()
for i in range(T):
  dot1()
end = timer()
t1 = end - start


#create timer for numpy array
start = timer()
for i in range(T):
  dot2()
end = timer()
t2 = end - start



print('time with list',t1)
print('time with list',t2)
print(t1/t2)

time with list 0.16525554500003636
time with list 0.001770008000676171
93.36429266811571


In [ ]:
#import a time calculator to see the difference
from timeit import default_timer as timer
#create an random array
a = np.random.randn(1000)
b = np.random.randn(1000)
#convert the above array's
c = tuple(a)
d = tuple(b)
T = 1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i]
  return dot
def dot2():
  return np.dot(a,b)
#take the timer
start = timer()
for i in range(T):
  dot1()
end = timer()
t1 = end - start


#create timer for numpy array
start = timer()
for i in range(T):
  dot2()
end = timer()
t2 = end - start



print('time with tuple',t1)
print('time with tuple',t2)
print(t1/t2)

time with tuple 0.184995235000315
time with tuple 0.0019006630000149016
97.33194942968038


28-05-2025

**Multi Dimensional Array's**

In [ ]:
import numpy as np


In [ ]:
#create a 2D Array
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
#How can we access from the 2D array?
#[row_index,column_index]
#print 1,2,3,4 from above array
print(a[0])
#How can we acess the values from particular column and particular row
print(a[1,2])
print(a[0,2])


[1 2 3 4]
7
3


In [ ]:
#How can i print the entire 1st column value from below array
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b[:,0])
#print all the values from second row.
print(b[1])
print(b[1,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 5 9]
[5 6 7 8]
[5 6 7 8]


In [ ]:
b = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(b)
print(b.shape)
print(b[0,0,1])

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4)
2


**Transpose**

In [ ]:
#transpose converts rows into columns and columns into rows
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b.T)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**Matrix Multiplication**

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
#applying the dot product
c = np.dot(a,b)
print(c)
print(a@b)

[[13 16]
 [29 36]]
[[13 16]
 [29 36]]


**Inverse**

In [ ]:
#find the inverse of an array a?
d = np.linalg.inv(b)
print(d)

[[-3.   2. ]
 [ 2.5 -1.5]]


In [ ]:
#How can i find the diagonal of array a?
e = np.diag(a)
print(e)

[1 4]


In [ ]:
#diagonal on vector returns the matrix
f = np.diag([1,4,5])
print(f)

[[1 0 0]
 [0 4 0]
 [0 0 5]]


In [ ]:
#print the values from the column 2 and 3
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b[:,1:3])
print(b[0:3,1:3])
print(b[:,-1:]) #print last column all the values in 2D form

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 4]
 [ 8]
 [12]]


**Boolean Indexing**

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
#print the numbers which is more than 2
print(a[a>2])
#print(a>2)

[[1 2]
 [3 4]
 [5 6]]
[3 4 5 6]


In [ ]:
l = (1,2,3,4)
print(l*2)

print(a*2)

(1, 2, 3, 4, 1, 2, 3, 4)
[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
#How can we apply a condition in array?
#np.where(condition,True,False)
c = np.where(a>2,a,-1)
print(c)


[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
#compute the indexes where the condition is true?
#np.argwhere()
i = np.argwhere(a>2)
print(i)

[[1 0]
 [1 1]
 [2 0]
 [2 1]]


In [ ]:
#[10,19,20,30,41,50,61] from above list compute the index of even numbers
a = np.array([10,19,20,30,41,50,61])
even = np.argwhere(a%2==0).flatten()  #flatten prints the o/p in single line
print(even)

[0 2 3 5]


In [ ]:
a_even =a[even]
print(a_even)

[10 20 30 50]


**Reshaping of an Array**

In [ ]:
#create a range of an array upto 9
a = np.arange(1,10)
print(a)


[1 2 3 4 5 6 7 8 9]


In [ ]:
b = a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#print a range of number from 1 to 10 and reshape it in to 5,2 columns
#print a range of number from 1 to 6 and reshape it in to 2 rows,3 columns
a = np.arange(10)
print(a)
b = a.reshape(5,2)
print(b)

c = np.arange(1,7)
d = c.reshape(2,3)

print(d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[1 2 3]
 [4 5 6]]


**np.newaxis**

In [ ]:
#newaxis:- is used to create a axis in the data
a = np.arange(1,7)
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
#newaxis
d = a[np.newaxis,:]
print(d)
print(d.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [ ]:
e = a[:,np.newaxis]
print(e)
print(e.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [ ]:
#np.array([])
#np.array([[]])
#np.shape
#np.size
#np.dtype
#np.itemsize
#np.dot(array1,array2)
#np.sqrt()
#np.linalg.inv(array1)
#np.where(condition,true,false)
#np.argwhere(condition)  (.flatten())
#np.arange(start,end)
#np.reshape(no.row,no.column)
#np.diag(array1 or [vector])
#np.newaxis
#Transpose(T)


29-05-2025

**Concatenation**

In [1]:
import numpy as np


In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
#combine or concatenate the above 2 arrays
#b.shape
c = np.concatenate((a,b),axis=None)
print(c)

[1 2 3 4 5 6]


In [3]:
c = np.concatenate((a,b),axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
d = np.concatenate((a,b.T),axis=1)
print(d)
#Note:- when we concatenate two array's along with the rows we need to check both array have same number of columns
#2.when we concatenate two array's along with the columns we need to check both array have same number of rows

[[1 2 5]
 [3 4 6]]


In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b),axis=1)
print(c)
#print the 1st row value
print(c[0,:])
print(c[0])

[[1 2 5 6]
 [3 4 7 8]]
[1 2 5 6]
[1 2 5 6]


In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b),axis=0)
print(c)
#print the 1st row value
print(c[0,:])
print(c[0])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2]
[1 2]


HSTACK-->Stack arrays in sequence horizentally

In [7]:
d = np.hstack((a,b))
print(d)

[[1 2 5 6]
 [3 4 7 8]]


In [8]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


VSTACK-->stack arrays in sequence vertically

In [9]:
#apply vstack on 1D array
v = np.vstack((arr1,arr2))
print(v)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
v = np.vstack((a,b))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


Copying of an array

In [12]:
a = np.array([1,2,3])
b = a
b[0]=42
print(a)
print(b)
#np.copy():- if you make any changes in the new array it won't impact on the old array

[42  2  3]
[42  2  3]


In [13]:
a = np.array([1,2,3])
b = a.copy()
b[0]=42
print(a)
print(b)

[1 2 3]
[42  2  3]


Data Types

In [14]:
#convert an array of int64 to int32
a = np.array([1,2,3,4],dtype='int32') #or dtype = np.int32
print(a)
print(a.dtype)

[1 2 3 4]
int32


In [15]:
b = np.array([1.5,2.5,3.5],dtype=np.float32)
print(b.dtype)

float32


Generating Array's

In [16]:
#generate an array's of zero with 2 rows and 3 columns
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
b = np.zeros(3)
print(b)

[0. 0. 0.]


In [18]:
#generate an array's of ones with 2 rows and 3cols
c = np.ones((2,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#generate an array of specific number with particular rows and columns
d = np.full((3,3),5)
print(d)
#np.full((rows,col),number)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [20]:
#generate an identity matrix
e = np.eye(3)
print(e)
f = np.identity(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#generate a range of numbers upto 9
i = np.arange(10)
print(i)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
#linspace:- splits the data into n equal parts
j = np.linspace(0,10,5)
print(j)
#np.linspace(start,end,no of partitions)

[ 0.   2.5  5.   7.5 10. ]


Random Numbers

In [23]:
#generate random numbers those are uniformly distributed from 0-1
a = np.random.random((3,2))
print(a)

[[0.5405709  0.36721162]
 [0.13105412 0.77991612]
 [0.74390721 0.71248009]]


In [24]:
#generate an array which is normally distributes or gussian distribution
b = np.random.randn(3,2)
print(b)
print(b.mean(),b.std(),b.var())

[[ 1.4522727  -0.47536107]
 [-0.3823876  -0.4950765 ]
 [ 0.32030192  1.00051301]]
0.2367104098366705 0.7630873530897054 0.5823023084454527


In [25]:
#generate an array of random numbers with 1000 and find the mean varience and std
c = np.random.randn(1000)
print(np.mean(c))
print(np.var(c))
print(np.std(c))

-0.012364194447467324
1.0604927729674563
1.0298022980006678


In [26]:
#generate an array of integers from 3,20 with 2 rows and 3 cols
d = np.random.randint(3,20,size=(2,3))
print(d)

[[ 5 16 15]
 [10 16  4]]


In [27]:
#generate an array of numbers upto 6 randomly with size of 10

e = np.random.choice(6,size=10)
print(e)

[5 3 3 4 1 1 4 5 3 5]


In [28]:
e = np.random.choice([3,5,7,9],size=10)
print(e)

[3 7 7 9 3 7 7 7 7 5]


In [29]:
#np.concatenate((arr1,arr2).axis=None,0,1)
#np.hstack((arr1,arr2))
#np.vstack((arr1,arr2))
#np.copy()
#change dtype of int64 and flot64-->np.array(l,dtype=np.int32)
#np.zeros((row,col))
#np.ones((row,col))
#np.full(row,col,number)
#np.eye(N)
#np.linspace(start,end,no of partitions)
#unifrom data-->np.random.random((row,col))
#normal distribution--> np.random.randn(row,col)
#how can you say a data is randomly distributed--> mean is zero, varience is equal to 1 and std is equal to 1
#random_numbers_with specific size-->np.random.choice(range of numbers,size=number)
#generate range of random integers-->np.random.randint(start,end, size=(row,col))
