<a href="https://colab.research.google.com/github/Srikanth-9492/My_python_notebook/blob/main/Numpy_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

27-05-2025

**Numpy Introduction**

In [ ]:
#what is Numpy?
#numpy is a core library for scientific computing in python
#what is the central object in numpy?
#Numpy - Array's
#what is Numpy?
#Array's are high performance multi dimensional objects which is designed for mathematical operations
#Array's are ordered, imuttable, and allows duplicate data


In [ ]:
#what are all different use cases of numpy?
"""1.  Dot Product/ Inner product
   2. Matric multiplication
   3. element wise matrix multiplication
   4. solving linear systems
   5. inverse
   6. determinent
   7. choose the random numbers
   8. statistics
   9. Broadcasting method """


** Installation of Numpy**

 what is pip?

 python package manager


 package ---> modules---> libraries----> inbuilt codes

In [1]:
!pip install Numpy

In [2]:
import numpy as np


In [3]:
#check the version of numpy?
np.__version__

'2.0.2'

In [4]:
#How many types of data structures do we have in numpy?
#There are 3 types
#1D--- Array's ---> Array's with zero columns and specific rows(axis 0)
#2D--- Array's ---> Array's with both rows(axis 0) and columns(axis 1)
#3D--- Array's ---> also known as Multidimensional arrays


**Central object in Numpy in Array**

In [5]:
#How can we create an array?
#Array's can be created from existing data
#1D --- Array
l = [1,2,3,4,5,6]
a = np.array(l)
print(a)

[1 2 3 4 5 6]


In [6]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [13]:
#I want to see the shape of the array
a.shape
#find the dtype of elements in the numpy array
a.dtype
#Find the dimensionality of an array
a.ndim
#Find the total no of elements present in array
a.size
#Find the memory size in bytes occupied by each element in array
a.itemsize

8

**Essential methods to create an array**

In [14]:
t = (1,2,3,4,5,6)
b = np.array(t)
print(b)
print(type(b))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [19]:
#create an array from dictionary?
d1 ={
     'name':'Medha',
     'course':'data science'
}
c = np.array(d1)
print(c)

{'name': 'Medha', 'course': 'data science'}


In [20]:
#create an array from the set?
s = {1,2,3,4,5,6,7,8}
d = np.array(s)
print(d)

{1, 2, 3, 4, 5, 6, 7, 8}


**Essential methods to access an array**

In [24]:
a = np.array([1,2,3,4])
#print the list value
print(a[0])
#print 2,3 from above array
print(a[1:3])
#reverse the above array
print(a[::-1])

1
[2 3]
[4 3 2 1]


In [25]:
#Array's are immutable we can replace the data but we cannot add new elements and we cannot remove elements from arrays.
a[2] = 5
print(a)

[1 2 5 4]


In [ ]:
#How can we add the new elements to the array?---> we can add by creating a new variable


**Element wise maths operation**

In [26]:
b = np.array([6,7,8,9])
print(a+b)
#what is vector addition?
#when we apply addition on array of same length n dimensions---> is known as vector addition
#Note:-

[ 7  9 13 13]


In [31]:
c = np.array([9])
print(b+c)
#What is broadcasting method?
#Adding a single element of an array with multiply elements in another array of same dimension is known as Broadcasting method


[15 16 17 18]


**Difference between Array and list**


In [35]:
l = [1,2,3]
a = np.array(l)
print(dir(a))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__

In [33]:
#adding the elements in the list:
l.append(4)
print(l)

[1, 2, 3, 4]


In [34]:
#add the element  in an array
b = np.array([5,6,7,8])
c = np.append(a,b)
print(c)

[1 2 3 5 6 7 8]


In [ ]:
"MISD---> Multiple input and single destination"


In [36]:
#find the sort of below array's?
a = np.array([10,20,30,40,50,60])
print(np.sqrt(a))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669]


**Dot Product**

In [37]:
a = np.array([1,2])
b = np.array([3,4])
dot = 0
for i in range(len(a)):
  dot = dot + a[i]*b[i]
print(dot)

11


In [39]:
#dot product is vector multiplication of elements and sum of the result
dot = np.dot(a,b)
print(dot)

11


In [40]:
#manual method
c = a*b
d = np.sum(c)
print(d)

11


In [41]:
#another method
e = a.dot(b)
print(e)

11


In [42]:
f = a@b
print(f)

11


**Speed test b/w Array vs List**

In [45]:
#import a time calculator to see the difference
from timeit import default_timer as timer
#create an random array
a = np.random.randn(1000)
b = np.random.randn(1000)
#convert the above array's
c = list(a)
d = list(b)
T = 1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i]
  return dot
def dot2():
  return np.dot(a,b)
#take the timer
start = timer()
for i in range(T):
  dot1()
end = timer()
t1 = end - start


#create timer for numpy array
start = timer()
for i in range(T):
  dot2()
end = timer()
t2 = end - start



print('time with list',t1)
print('time with list',t2)
print(t1/t2)

time with list 0.16525554500003636
time with list 0.001770008000676171
93.36429266811571


In [46]:
#import a time calculator to see the difference
from timeit import default_timer as timer
#create an random array
a = np.random.randn(1000)
b = np.random.randn(1000)
#convert the above array's
c = tuple(a)
d = tuple(b)
T = 1000
def dot1():
  dot = 0
  for i in range(len(c)):
    dot += c[i]*d[i]
  return dot
def dot2():
  return np.dot(a,b)
#take the timer
start = timer()
for i in range(T):
  dot1()
end = timer()
t1 = end - start


#create timer for numpy array
start = timer()
for i in range(T):
  dot2()
end = timer()
t2 = end - start



print('time with tuple',t1)
print('time with tuple',t2)
print(t1/t2)

time with tuple 0.184995235000315
time with tuple 0.0019006630000149016
97.33194942968038
