<a href="https://colab.research.google.com/github/Srikanth-9492/My_python_notebook/blob/main/Practise_session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Object oriented Programming language

In [ ]:
a = "hello"
print(type(a))
#How we can categorize it is a string or How we can define it is a string?
#what is the properties of a?
#a is declaring a text in ""
#length of text is 5
#what are all methods we can apply on "a"?
#upper(),lower(),zfill(),title()
#dir()--->by default returns all methods applicable on object

<class 'str'>


In [ ]:
#if we want to build our own classes and object we use four rules or 4 pillars
#The four pillars of the OOP's

**Encapsulation**---> wrapping the data(variables) and methods
(functions) together into a single class

--> it also restricts direct access to some variables using private or
protected access

ex:- A bank account ---> we can deposit the money, or with withdraw
money by using the methods

can we directly change the account balance ---> No


In [ ]:
class Bank_Account:
  def __init__(self,owner,balance):
    self.owner = owner
    self.balance = balance
    #self is a pointer or referncer
  #methods - is nothing but functions created inside the class
  def deposit(self,amount):
    if amount>0:
      self.balance += amount
      print(f"deposited :{amount}")
    else:
      print("Invalid Deposit Amount")
  def withdraw(self,amount):
    if amount<=self.balance:
      self.balance -= amount
      print(f"withdraw :{amount}")
    else:
      print("Insuffiecient balance")
#create an object
account1 = Bank_Account("Abhi",1000)
account1.deposit(2000)
print(account1.__gt__)

deposited :2000
<method-wrapper '__gt__' of Bank_Account object at 0x77fc5bbaa540>


In [ ]:
print(dir(account1))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'balance', 'deposit', 'owner', 'withdraw']


In [ ]:
#encapsulation (data hiding + controlled access)

**Abstraction**--> Hiding the implementation details and showing only
the necessary features

this can be achieved using abstract classes and methods


ex:-


In [8]:
account1.withdraw(1000)
#abstraction Hide details of how the bank can deposit and withdrawn amount but expose only the methods

withdraw :1000


**Inheritance** --> One class can inherit properties and methods from
another class

ex:- child inherits traits from parents

In [10]:
class person:
  def __init__(self,name):
    self.name = name
  def display(self):
    print(f"name : {self.name}")
class student(person):  #inherit from person class
  def __init__(self,name,student_id):
    super().__init__(name)  #super() means i am inheriting the attributes from the parent class
    self.student_id = student_id
  def display(self):  #over-riding method
      print(f"name : {self.name},ID: {self.student_id}")

p1 = person("areef")
p1.display()

s1 = student("met",101)
s1.display()

#over-riding method :- when a child class provides a new implementation of method that is already exist in parent class
#so the child class replace or override the parent class methods when we called on child class object

name : areef
name : met,ID: 101


**Polymorphism** --> One method behvave differently based on object
(many forms)

In [11]:
import numpy as np

In [12]:
#create an array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
#2.np.arange(start,end,step):- create a range of values
#create range of even number array upto 10
a = np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [14]:
#3.np.linspace(start,stop,size):-create evenly spaced values or creates eqiually distributed values
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
#4.np.reshape(rows,columns):- change array shape
#create range of array from 1 to 10 and shape it in to 3 rows and 3 columns
a = np.arange(1,10).reshape(3,3)
print(a)
#np.reshape converts 1D array to 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
#5.np.zeros()
zero =np.zeros((3,3))
print(zero)
ones = np.ones((3,3))
print(ones)

a = np.full((3,3),5)
print(a)

b = np.eye(3)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#6.np.random.random():-  uniform distribution random values ranging from o to 1
a = np.random.random((3,3))
print(a)

[[0.5527191  0.21484384 0.94086592]
 [0.14694059 0.12854327 0.85232867]
 [0.76738924 0.64301629 0.94747084]]


In [26]:
#7.np.random.randn()--> generates normal distributed data
#np.random.randint()
a = np.random.randint(1,10,size=(5,2))
print(a)

[[7 5]
 [2 1]
 [2 2]
 [8 9]
 [8 3]]


In [27]:
#8.np.mean(),np.median(),np.std()
a = np.array([10,20,30,40,50])
print(a.mean())
print(np.mean(a))

30.0
30.0


In [29]:
#9.dot product / @ operator :- matrix  multiplication
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a@b)
print(np.dot(a,b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [30]:
#10.np.concatenate(),np.vstack(),np.hstack()
print(np.concatenate([a,b],axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [31]:
print(np.hstack([a,b]))
print(np.vstack([a,b]))


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [33]:
#11. np.ndim, np.shape, np.dtype, np.itemsize
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size) #total number of elements in the array

#np.where() --> used to apply the condition
#np.argwhere() --> is used to compute the indices where the condition is true

2
(2, 2)
int64
4


In [34]:
#get the even numbers from array "a"
a = np.array([[1,2],[3,4]])
eve = np.where(a%2==0,a,-1)
print(eve)

[[-1  2]
 [-1  4]]


In [40]:
a = np.ndarray((2,3),dtype=int)
print(a)

[[729061092         0         0]
 [        0         0         0]]
